### ISSUE TITLE
fixed cannot find User class.

### ISSUE THREAD

**Issue by linkerlin** [fengyouchao/esocks#1] opened 2015-09-07 16:08 UTC
diff --git a/src/main/java/io/github/fengyouchao/esocks/Application.java b/src/m
index de0c2f7..ab335f4 100755
--- a/src/main/java/io/github/fengyouchao/esocks/Application.java
+++ b/src/main/java/io/github/fengyouchao/esocks/Application.java
@@ -32,7 +32,7 @@ import fucksocks.server.GenericSocksProxyServer;
 import fucksocks.server.SSLSocksProxyServer;
 import fucksocks.server.Socks5Handler;
 import fucksocks.server.SocksProxyServer;
-import fucksocks.server.User;
+import fucksocks.server.manager.User;
 import fucksocks.server.UsernamePasswordAuthenticator;
 import fucksocks.server.filters.IPSessionFilter;
 import fucksocks.server.filters.IPSessionFilter.Mode;

**Comment by fengyouchao** [comment] 2015-09-08 04:54
This bug is caused by the SOCKS library [Fucksocks](https://github.com/fengyouchao/fucksocks). I have moved class `User` from package `fucksocks.server` to `fucksocks.server.manager` in [Fucksocks](https://github.com/fengyouchao/fucksocks).

**Comment by fengyouchao** [comment] 2015-09-08 05:05
Thank for your PR. I have merged it into master.

**Closed as completed** 2015-09-08 05:05 UTC
Labels: bug
